import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
  mkdirSync,
  writeFileSync,
  createReadStream,
  createWriteStream,
} from "node:fs";
import { join } from "node:path";
import { createInterface } from "node:readline";
import picocolors from "picocolors";

// ── Types ──

export type ExportFormat = "instruction" | "messages";

export interface ExportOptions {
  output: string;
  format: ExportFormat;
  name?: string;
  verbose?: boolean;
}

interface TrainingExample {
  id: string;
  type: string;
  repo: string;
  file: string;
  instruction: string;
  input: string;
  output: string;
}

interface ExamplesSummary {
  totalExamples: number;
  totalFilesProcessed: number;
  totalFilesSkipped: number;
  reposProcessed: number;
  mode: string;
  examplesByType: Record<string, number>;
  generatedAt: string;
}

interface ExportStats {
  totalExamples: number;
  totalSizeBytes: number;
  format: ExportFormat;
  examplesByType: Record<string, number>;
  sourceRepos: number;
  languages: string[];
}

interface ExportMetadata {
  name: string;
  description: string;
  examples: number;
  format: ExportFormat;
  languages: string[];
  sourceRepos: number;
  license: string;
  created: string;
  generatedBy: string;
  version: string;
}

// ── Format conversion ──

interface InstructionExample {
  instruction: string;
  input?: string;
  output: string;
}

interface MessageExample {
  messages: Array<{ role: string; content: string }>;
}

function toInstruction(ex: TrainingExample): InstructionExample {
  const entry: InstructionExample = {
    instruction: ex.instruction,
    output: ex.output,
  };
  if (ex.input && ex.input.trim().length > 0) {
    entry.input = ex.input;
  }
  return entry;
}

function toMessages(ex: TrainingExample): MessageExample {
  let userContent = ex.instruction;
  if (ex.input && ex.input.trim().length > 0) {
    userContent += "\n\n" + ex.input;
  }
  return {
    messages: [
      { role: "user", content: userContent },
      { role: "assistant", content: ex.output || "(to be filled)" },
    ],
  };
}

// ── Language inference from example types ──

const TYPE_LANGUAGE_MAP: Record<string, string[]> = {
  function_explain: ["TypeScript", "JavaScript"],
  type_definition: ["TypeScript"],
  error_context: ["TypeScript"],
  test_assertion: ["TypeScript", "JavaScript"],
  error_handling: ["TypeScript", "JavaScript"],
  file_context: ["TypeScript", "JavaScript"],
  doc_context: ["Markdown"],
};

function inferLanguages(examplesByType: Record<string, number>): string[] {
  const langs = new Set<string>();
  for (const type of Object.keys(examplesByType)) {
    const mapped = TYPE_LANGUAGE_MAP[type];
    if (mapped) {
      for (const l of mapped) langs.add(l);
    }
  }
  // If nothing specific, default to TypeScript/JavaScript
  if (langs.size === 0) langs.add("TypeScript");
  return Array.from(langs).sort();
}

// ── README generation ──

function generateReadme(meta: ExportMetadata, stats: ExportStats): string {
  const tags = [
    ...meta.languages.map((l) => l.toLowerCase()),
    "code",
    "reposift",
    meta.format === "messages" ? "chat" : "instruction",
  ];
  const yamlTags = tags.map((t) => `    - ${t}`).join("\n");

  return `---
license: ${meta.license}
language:
  - en
tags:
${yamlTags}
task_categories:
  - text-generation
---

# ${meta.name}

${meta.description}

## Dataset Overview

| Property | Value |
|----------|-------|
| Examples | ${meta.examples.toLocaleString()} |
| Format | ${meta.format === "messages" ? "Chat messages (OpenAI-compatible)" : "Instruction/Input/Output"} |
| Languages | ${meta.languages.join(", ") || "Mixed"} |
| Source Repos | ${meta.sourceRepos} |
| License | ${meta.license} |
| Created | ${meta.created} |
| Generated by | ${meta.generatedBy} v${meta.version} |

## Example Types

${Object.entries(stats.examplesByType)
  .sort((a, b) => b[1] - a[1])
  .map(([type, count]) => `| ${type} | ${count.toLocaleString()} | ${(count / stats.totalExamples * 100).toFixed(1)}%`)
  .join("\n")}

## Consumption

This dataset is model-agnostic and can be used with any training framework:

**Hugging Face:**
\`\`\`bash
python -c "
from datasets import load_dataset
dataset = load_dataset('json', data_files='dataset.jsonl')
"
\`\`\`

**OpenAI Fine-tuning:**
\`\`\`bash
openai api fine_tuning.jobs.create \\
  --training-file dataset.jsonl \\
  --model gpt-4o-mini
\`\`\`

**MLX:**
\`\`\`bash
mlx_lm.lora --train \\
  --data ./dataset.jsonl
\`\`\`

**LlamaFactory:**
\`\`\`yaml
# dataset_info.yaml
reposift_dataset:
  file_name: dataset.jsonl
  format: ${meta.format === "messages" ? "chat" : "instruction"}
\`\`\`

## Files

- \`dataset.jsonl\` — Training examples in ${meta.format} format
- \`metadata.json\` — Dataset metadata
- \`stats.json\` — Detailed statistics

Generated by ${meta.generatedBy} v${meta.version} on ${meta.created}
`;
}

// ── Main ──

export async function exportCommand(
  inputPath: string,
  options: ExportOptions,
): Promise<void> {
  const resolvedInput = join(process.cwd(), inputPath);
  const resolvedOutput = join(process.cwd(), options.output);

  const format: ExportFormat = options.format ?? "instruction";
  const datasetName = options.name ?? "reposift-dataset";

  if (options.verbose) {
    console.log(`${picocolors.dim("▸")} Format: ${picocolors.white(format)}`);
    console.log(`${picocolors.dim("▸")} Name:   ${picocolors.white(datasetName)}`);
  }

  console.log(`\n${picocolors.bold(picocolors.cyan("Exporting Dataset"))}`);
  console.log(picocolors.dim("═".repeat(50)));
  console.log(`  ${picocolors.bold("Input:")}   ${picocolors.dim(resolvedInput)}`);
  console.log(`  ${picocolors.bold("Output:")}  ${picocolors.white(resolvedOutput)}`);
  console.log(`  ${picocolors.bold("Format:")}  ${picocolors.white(format)}`);

  if (!existsSync(resolvedInput)) {
    console.error(`\n${picocolors.red("✘")} Input not found: "${resolvedInput}"`);
    process.exitCode = 1;
    return;
  }

  // Find the training files
  const trainingFile = join(resolvedInput, "training.jsonl");
  const examplesFile = join(resolvedInput, "examples.jsonl");
  const summaryFile = join(resolvedInput, "examples_summary.json");

  const inputFile = existsSync(trainingFile) ? trainingFile
    : existsSync(examplesFile) ? examplesFile
    : null;

  if (!inputFile) {
    console.error(
      `\n${picocolors.red("✘")} No training files found in "${resolvedInput}".\n` +
        "  Expected training.jsonl or examples.jsonl from 'reposift prepare'.",
    );
    process.exitCode = 1;
    return;
  }

  // Read summary if available
  let summary: ExamplesSummary | null = null;
  if (existsSync(summaryFile)) {
    try {
      summary = JSON.parse(readFileSync(summaryFile, "utf-8"));
    } catch {
      // best effort
    }
  }

  // Prepare output
  mkdirSync(resolvedOutput, { recursive: true });

  const datasetPath = join(resolvedOutput, "dataset.jsonl");
  const writer = createWriteStream(datasetPath, { flags: "w" });

  // Read input line by line and convert
  const reader = createInterface({
    input: createReadStream(inputFile),
    crlfDelay: Infinity,
  });

  let totalExamples = 0;
  let totalSizeBytes = 0;
  let examplesByType: Record<string, number> = {};
  const repoSet = new Set<string>();

  for await (const line of reader) {
    if (!line.trim()) continue;

    let ex: TrainingExample;
    try {
      ex = JSON.parse(line);
    } catch {
      continue;
    }

    // Validate minimum structure
    if (!ex.instruction || typeof ex.instruction !== "string") continue;

    // Skip examples with no output (can't generate meaningful assistant response)
    if (!ex.output || ex.output.trim().length === 0) {
      examplesByType["skipped_no_output"] = (examplesByType["skipped_no_output"] ?? 0) + 1;
      continue;
    }

    // Convert to target format
    const converted = format === "messages" ? toMessages(ex) : toInstruction(ex);
    const jsonLine = JSON.stringify(converted) + "\n";
    writer.write(jsonLine);

    totalExamples++;
    totalSizeBytes += Buffer.byteLength(jsonLine, "utf-8");

    // Track type
    if (ex.type) {
      examplesByType[ex.type] = (examplesByType[ex.type] ?? 0) + 1;
    } else {
      examplesByType["unknown"] = (examplesByType["unknown"] ?? 0) + 1;
    }

    // Track unique repos
    if (ex.repo) repoSet.add(ex.repo);
  }

  // Close writer
  await new Promise<void>((resolve, reject) =>
    writer.end((err: Error | undefined) => (err ? reject(err) : resolve())),
  );

  // Build stats
  const inferredLanguages = inferLanguages(examplesByType);
  const sourceRepos = summary?.reposProcessed ?? repoSet.size;

  const stats: ExportStats = {
    totalExamples,
    totalSizeBytes,
    format,
    examplesByType,
    sourceRepos,
    languages: inferredLanguages,
  };

  // Write stats.json
  writeFileSync(
    join(resolvedOutput, "stats.json"),
    JSON.stringify(stats, null, 2),
  );

  // Write metadata.json
  const created = summary?.generatedAt
    ? summary.generatedAt.split("T")[0]
    : new Date().toISOString().split("T")[0];

  const metadata: ExportMetadata = {
    name: datasetName,
    description: `RepoSift training dataset — ${format} format. ${totalExamples.toLocaleString()} examples across ${inferredLanguages.join(", ")}.`,
    examples: totalExamples,
    format,
    languages: inferredLanguages,
    sourceRepos,
    license: "mixed",
    created,
    generatedBy: process.env.npm_package_name || "RepoSift",
    version: process.env.npm_package_version || "0.1.0",
  };

  writeFileSync(
    join(resolvedOutput, "metadata.json"),
    JSON.stringify(metadata, null, 2),
  );

  // Write README.md
  const readme = generateReadme(metadata, stats);
  writeFileSync(join(resolvedOutput, "README.md"), readme);

  // Print summary
  const sizeMB = (totalSizeBytes / (1024 * 1024)).toFixed(2);

  console.log(`\n${picocolors.bold(picocolors.green("Export Complete"))}`);
  console.log(picocolors.dim("═".repeat(50)));
  console.log(`  ${picocolors.bold("Examples:")}  ${picocolors.white(totalExamples.toLocaleString())}`);
  console.log(`  ${picocolors.bold("Size:")}      ${picocolors.white(`${sizeMB} MB`)}`);
  console.log(`  ${picocolors.bold("Repos:")}     ${picocolors.white(sourceRepos.toLocaleString())}`);
  console.log(`  ${picocolors.bold("Format:")}    ${picocolors.white(format)}`);
  console.log(picocolors.dim("═".repeat(50)));

  const typeEntries = Object.entries(examplesByType).sort((a, b) => b[1] - a[1]);
  if (typeEntries.length > 0) {
    console.log(`\n${picocolors.bold("Examples by Type:")}`);
    for (const [type, count] of typeEntries) {
      const pct = ((count / totalExamples) * 100).toFixed(1);
      console.log(
        `  ${picocolors.cyan(type.padEnd(25))} ${picocolors.white(count.toLocaleString().padStart(10))}  ${picocolors.dim(`(${pct}%)`)}`,
      );
    }
  }

  console.log(`\n  ${picocolors.dim("Output files:")}`);
  console.log(`    ${picocolors.cyan("dataset.jsonl")}    — ${totalExamples.toLocaleString()} examples (${format} format)`);
  console.log(`    ${picocolors.cyan("metadata.json")}    — dataset metadata`);
  console.log(`    ${picocolors.cyan("stats.json")}       — detailed statistics`);
  console.log(`    ${picocolors.cyan("README.md")}        — documentation & usage examples`);

  console.log(`\n  ${picocolors.dim("Consume with:")}`);
  if (format === "messages") {
    console.log(`    ${picocolors.white("openai api fine_tuning.jobs.create --training-file dataset.jsonl")}`);
  }
  console.log(`    ${picocolors.white("python -c \"from datasets import load_dataset; dataset = load_dataset('json', data_files='dataset.jsonl')\"")}`);
  console.log(`    ${picocolors.white("mlx_lm.lora --train --data ./dataset.jsonl")}`);
  console.log("");
}
